### ISSUE TITLE
loads method now produces unicode string

### ISSUE THREAD

**Issue by markoh1** [simplejson/simplejson#190] opened 2017-11-10 10:27 UTC
loads method now produces unicode strings. Is this change intentional?

Before 3.12:

```
Python 2.7.14 (default, Sep 27 2017, 05:42:32)
[GCC 6.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import simplejson as json
>>> json.loads('{"a":1}')
{'a': 1}
```

Ver. 3.12:

```
>>> import simplejson as json
>>> json.loads('{"a":1}')
{u'a': 1}
```

**Comment by etrepum** [comment] 2017-11-10 16:29
This looks like you installed a version without the speedups. How did you install it?

**Comment by markoh1** [comment] 2017-11-10 17:55
Right, speedups are not installed (I am installing with pip install simplejson).

But, if I switch back to previous version (pip install simplejson==3.11.1) speedups get installed.

Tested on ubuntu 16.04 and centos7.

**Comment by serhiy-storchaka** [comment] 2017-11-10 20:41
Seems this is partially a duplicate of #185 (there is a problem with the speedups in PyPI package).

I don't know whether it is worth to fix this difference between the Python and C implementations (this is an optimization of the C implementation). In standard `json` module both implementations return Unicode strings.

**Comment by etrepum** [comment] 2017-11-10 21:01
It's unclear to me why the C extension isn't getting built for some people, and PyPI is having problems right now so I don't think I can roll back the release.

**Comment by markoh1** [comment] 2017-11-10 21:18
What are the requirements for C speedups? I have python-devel and gcc installed (+ dependecies provided by yum/apt). Speedups have worked in previous versions. I'll stay on ver. 3.11.1 for now.

**Comment by etrepum** [comment] 2017-11-10 22:21
There should be no requirements other than a working C compiler. This could be a regression in pip for all I know. I do not have time to investigate today.

**Comment by etrepum** [comment] 2017-11-23 19:47
Alright it seems that the problem was that somehow source-only wheels got uploaded. I was unable to resolve by removing those files from pypi this until today as my pypi account was locked (throttled due to hacking attempts I guess) and I had to go through support to get it unlocked. I'll check the scripts before the next release to ensure that that kind of wheel does not get uploaded again.

**Closed** 2017-11-23 21:38 UTC
